### ISSUE TITLE
list from wildcard ',' is not sorted after parsing

### ISSUE THREAD

**Issue by lukexu** [pitchblack408/pyawscron#46]
Hi,

We found the allowed list parsed from the wildcard ',' is not sorted. Thus when a datetime is not listed before someone later than it, it will be missed in the results of next().

Please check the following code.  Maybe it can work by simply sorting on allows returned by __parse_one_rule(self, rule, min, max)
```python
import pyawscron
import datetime
sche = AWSCron('5,4 * * * ? *')
now = datetime.datetime.now(tz=datetime.timezone.utc)
print(now)
> 2021-09-26 04:09:13.573197+00:00
sche.occurrence(now).next()
> datetime.datetime(2021, 9, 26, 5, 5, tzinfo=datetime.timezone.utc)

```

**Comment by pitchblack408** [comment]
So, I noticed that you have 5,4 instead of 4,5. Is that even possible in AWS Cron?  I need to double check that first before I make a change.

**Comment by lukexu** [comment]
Thanks for the quick reply. I think it works for AWS.
![image](https://user-images.githubusercontent.com/9958416/135212548-7ace558d-0c86-4690-90dc-9769d98fcb99.png)

**Comment by pitchblack408** [comment]
Making a new release with the fix
