### ISSUE TITLE
Bug: Undeclared dependencies

### ISSUE THREAD

**Issue by FollowTheProcess** [pitchblack408/pyawscron#48]
Hi there!

Just trying out your project for something I'm doing at the moment and had some installation issues (missing `python-dateutil`) I think I've found the cause though.

In your `requirements.txt` you specify that you depend on `python-dateutil` here: https://github.com/pitchblack408/pyawscron/blob/e52f5fd5e00936d06a781cc8ada23cbc9ba6a570/requirements.txt#L1

But this is not read by pip at install time, `setup.py` is and in there you don't include the requirements section: https://github.com/pitchblack408/pyawscron/blob/e52f5fd5e00936d06a781cc8ada23cbc9ba6a570/setup.py#L17-L37

I would suggest the following change:

* Remove `requirements.txt`
* Add the following to `setup.py`:

```python
setuptools.setup(
    <other args omitted>,
    install_requires=["python-dateutil~=2.8.1"]    
)
```
You also don't need to specify setuptools here, as this is covered by the build-system in pyproject.toml.

I'd be happy to do a PR if you like?

**Comment by pitchblack408** [comment]
Thanks
