### ISSUE TITLE
Bug: Assigning 'month' attribute throws error

### ISSUE THREAD

**Issue by sonyal** [pitchblack408/pyawscron#55]
If the cron expression is '1 2 3 * 5 2022', **there is no error**.
If the expression is '1 2 3 4 5 2022' and I use it in:

- get_all_schedule_bw_dates()- throws error "TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'"
- get_next_n_schedule()- throws error "AttributeError: 'NoneType' object has no attribute 'tzinfo'"
- occurence().next()- no error but the value is None

**Comment by pitchblack408** [comment]
Thank you for reporting the issue, it will be a bit for me to look into the issue.

**Comment by pitchblack408** [comment]
So, I looked at it and when you set all the fields without a wild card to a value, its like creating a single date.  The expression is '1 2 3 4 5 2022' would not return a range of dates, but the date itself.   I will look at the code to see about avoiding the exception.

**Comment by pitchblack408** [comment]
merged changes to dev branch

**Comment by pitchblack408** [comment]
Change was implemented in release 1.0.6
