### ISSUE TITLE
Handling of non-existent dates inconsistent with AWS EventBridge

### ISSUE THREAD

**Issue by ghost** [pitchblack408/pyawscron#56]
A little while back I brought it to Amazon's attention that its handling of non-existent dates (February 31st, June 31st, etc.) was causing the page to crash. For example, the expression `0 0 31W * ? 2023` would break the page. Amazon responded and changed the handling of the `W` wildcard to skip the month entirely in the case where the specified number does not exist. For example, `0 0 31W * ? 2023` should theoretically be 2023-02-28, but since 2023-02-31 does not exist the month is skipped outright. 

This library handles non-existent dates by throwing this error `ValueError: day is out of range for month` instead of just skipping the month and moving on. A good test for this would be to view the results of `0 0 31W * ? 2024`. It correctly calls out the first execution on 2024-01-31 00:00:00+00:00 but then crashes when it gets to February with that `ValueError`. Expected behavior would be to move on to march and not count an execution for February.

**Comment by pitchblack408** [comment]
Hi, I am sorry about the long delay in looking into this.  Too focus on regular work.  I will look at this today

**Comment by pitchblack408** [comment]
Changes were pushed to dev, but build failed. I will Look into it today.

**Comment by pitchblack408** [comment]
Change was implemented in release 1.0.6
