### ISSUE TITLE
Possibly update 'python-dateutil' dependency?

### ISSUE THREAD

**Issue by kazie** [pitchblack408/pyawscron#65]
Hi,

I have a project where I use `pyawscron` in my dev/tests, and `python-dateutil` in the project.

I cannot update `python-dateutil` to the latest [^2.9.0](https://pypi.org/project/python-dateutil/2.9.0/) as this project in `requirements.txt` file is locked to:
```
python-dateutil~=2.8.1
```

Which gives me the error of (through [Poetry](https://python-poetry.org/)):
```
Because pyawscron (1.0.4) depends on python-dateutil (≥2.8.1,<2.9.0)
```

---

In [the release notes](https://github.com/dateutil/dateutil/releases/tag/2.9.0) I would not assume any breaking changes - so maybe it could be updated here as well, to allow feature update of `2.9.x`?

i.e. either upgrading it here, or making the requirements less stringent? 

_On the other hand_, I could remove my tests, and this dependency, but I feel that it is not the better way forward.

Thanks for providing this tool overall! :smile:

**Comment by pitchblack408** [comment]
I made the change and pyawscron 1.0.7 was released

**Comment by pitchblack408** [comment]
I made the change and pyawscron 1.0.7 was released

**Comment by kazie** [comment]
Thank you very much!
